### ISSUE TITLE
how to interact with the installed nvm

### ISSUE THREAD

**Issue by peterdutton** [artberri/puppet-nvm#20]
Hi,

I want to run an 'exec' command against my installation of nvm to make it install the latest version of npm after nvm is installed. In my manifest I have the following:

```
  class { 'nvm':
    user =>  'root',
    nvm_dir =>  '/opt/nvm',
    version =>  'v0.34.0',
    profile_path =>  '/etc/profile.d/nvm.sh',
    install_node =>  '6.11.3',
  }

  exec { "install latest npm":
    path => "/opt/nvm",
    command => "nvm install-latest-npm",
    require => [Class["nvm"]],
  }
```
However, when I try to provision using this I get the error:

`Could not find command 'nvm'`

Do you know of a way that I can run an exec against nvm? I am aware that because it's script-based it doesn't behave like a 'traditional' command-line tool (e.g. in terms of being recognised by commands like 'which').

**Comment by manuelkiessling** [comment]
@peterdutton As you've said, `nvm` cannot be called directly through Puppet's `exec`, because it is a shell function and not a "physical" executable, and therefore it cannot be called with an absolute path, which is required for the `command` parameter of exec.

I have worked around this by creating a wrapper script in `/opt/nvm.sh` (which I provision through Puppet, obviously), like this:

    #!/usr/bin/env bash
    
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

    nvm "$@"

I can then use it like this:

    /opt/nvm.sh install 16

    /opt/nvm.sh exec 16 npm install elasticdump

    /opt/nvm.sh exec 16 elasticdump

That gives me a physical executable which I can execute through Puppet.

**Comment by artberri** [comment]
This plugin is not maintained anymore, sorry for the inconvenience:
https://github.com/artberri/puppet-nvm?tab=readme-ov-file#deprecated-puppet-nvm
